---
  - hosts: localhost
    connection: local 
    become: yes
    gather_facts: true
    vars_files:
    - ~/myportal_ansible/inventory/staging/group_vars/all/server.yml
    roles:
      - role: packages
        tags: packages
      - role: myportal
        tags: myportal
